# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "make_exportable"
  s.version = "1.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kevin Skoglund", "Matthew Bergman"]
  s.date = "2012-02-10"
  s.description = "MakeExportable is a Rails gem/plugin to assist in exporting application data as CSV, TSV, JSON, HTML, XML or Excel. Filter and limit the data exported using ActiveRecord. Export returned values from instance methods as easily as database columns."
  s.email = "kevin@novafabrica.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/make_exportable.rb",
    "lib/make_exportable/core.rb",
    "lib/make_exportable/errors.rb",
    "lib/make_exportable/exportable_format.rb",
    "lib/make_exportable/exportable_formats/csv.rb",
    "lib/make_exportable/exportable_formats/excel.rb",
    "lib/make_exportable/exportable_formats/html.rb",
    "lib/make_exportable/exportable_formats/json.rb",
    "lib/make_exportable/exportable_formats/tsv.rb",
    "lib/make_exportable/exportable_formats/xml.rb",
    "lib/make_exportable/make_exportable_helper.rb",
    "lib/make_exportable/version.rb",
    "rails/init.rb",
    "spec/database.yml.sample",
    "spec/make_exportable/formats_spec.rb",
    "spec/make_exportable/make_exportable_helper_spec.rb",
    "spec/make_exportable/make_exportable_spec.rb",
    "spec/models.rb",
    "spec/schema.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/novafabrica/make_exportable"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Makes any Rails model easily exportable"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

