# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{make_exportable}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kevin Skoglund", "Matthew Bergman"]
  s.date = %q{2010-06-21}
  s.description = %q{MakeExportable is a Rails gem/plugin to assist in exporting application data as CSV, TSV, JSON, HTML, XML or Excel. Filter and limit the data exported using ActiveRecord. Export returned values from instance methods as easily as database columns.}
  s.email = %q{kevin@novafabrica.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/make_exportable.rb",
     "lib/make_exportable/core.rb",
     "lib/make_exportable/errors.rb",
     "lib/make_exportable/exportable_format.rb",
     "lib/make_exportable/exportable_formats/csv.rb",
     "lib/make_exportable/exportable_formats/excel.rb",
     "lib/make_exportable/exportable_formats/html.rb",
     "lib/make_exportable/exportable_formats/json.rb",
     "lib/make_exportable/exportable_formats/tsv.rb",
     "lib/make_exportable/exportable_formats/xml.rb",
     "lib/make_exportable/make_exportable_helper.rb",
     "lib/make_exportable/version.rb",
     "rails/init.rb",
     "spec/database.yml.sample",
     "spec/make_exportable/formats_spec.rb",
     "spec/make_exportable/make_exportable_helper_spec.rb",
     "spec/make_exportable/make_exportable_spec.rb",
     "spec/models.rb",
     "spec/schema.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/novafabrica/make_exportable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Makes any Rails model easily exportable}
  s.test_files = [
    "spec/make_exportable/formats_spec.rb",
     "spec/make_exportable/make_exportable_helper_spec.rb",
     "spec/make_exportable/make_exportable_spec.rb",
     "spec/models.rb",
     "spec/schema.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

