# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{make_exportable}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kevin Skoglund", "Matthew Bergman"]
  s.date = %q{2010-05-28}
  s.description = %q{MakeExportable is a Rails Gem/Plugin that makes exporting your model's data effortless. It works in a variety of formats and can filter down what gets exported using ActiveRecord's find method.}
  s.email = %q{matt@novafabirca.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/make_exportable.rb",
     "lib/nova_fabrica/make_exportable.rb",
     "lib/nova_fabrica/make_exportable_errors.rb",
     "lib/nova_fabrica/make_exportable_helper.rb",
     "rails/init.rb",
     "spec/database.yml",
     "spec/database.yml.sample",
     "spec/make_exportable/make_exportable_spec.rb",
     "spec/models.rb",
     "spec/schema.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/Fotoverite/make-exportable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Export your model's data effortless}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

